const routes={home:'/',technology:'/technology',realEstate:'/real-estate',webDesign:'/web-design'};
const logo=`<svg viewBox="0 0 384 82" role="img" aria-label="OpenGate Advisory"><rect x="2" y="8" width="58" height="58" rx="5" fill="#06111a" stroke="rgba(237,246,255,.28)" stroke-width="2"/><path d="M15 20h33v33h-10V37.5L20.5 55 13 47.5 30.5 30H15z" fill="#d2ad4f"/><text x="74" y="39" fill="#edf6ff" font-family="Manrope,Arial" font-size="30" font-weight="800" letter-spacing="-1.6">OpenGate</text><text x="76" y="63" fill="#d2ad4f" font-family="Manrope,Arial" font-size="19" font-weight="400">Advisory</text></svg>`;
const path=location.pathname.replace(/\.html$/,'').replace(/\/$/,'')||'/';
const header=document.querySelector('[data-site-header]');
const footer=document.querySelector('[data-site-footer]');
if(header)header.innerHTML=`<header class="site-header"><div class="nav-inner"><a class="brand" href="/" aria-label="OpenGate Advisory home">${logo}</a><button class="nav-toggle" aria-label="Open menu" aria-expanded="false">☰</button><nav class="nav-links" aria-label="Main navigation"><a class="nav-link" href="/#services">Services</a><a class="nav-link" href="/#team">Team</a><div class="portfolio-menu"><button class="nav-trigger ${['/technology','/real-estate','/web-design'].includes(path)?'active':''}" aria-expanded="false">Portfolio <span class="nav-arrow" aria-hidden="true"></span></button><div class="dropdown"><a href="/technology">Technology<small>Morbit smart building intelligence</small></a><a href="/real-estate">Real Estate<small>Bellevue Residencies, Sri Lanka</small></a><a href="/web-design">Web Design<small>Websites and content creation</small></a></div></div><a class="nav-link" href="/#contact">Contact</a><a class="nav-link nav-cta" href="https://outlook.office.com/book/DiscoveryCall30minutes@morbit.co.uk/" target="_blank" rel="noopener">Book a Call</a></nav></div></header>`;
if(footer)footer.innerHTML=`<footer class="site-footer"><div class="footer-inner"><div class="footer-brand">OpenGate <span>Advisory</span></div><div class="footer-links"><a href="/#services">Services</a><a href="/#team">Team</a><a href="/technology">Technology</a><a href="/real-estate">Real Estate</a><a href="/web-design">Web Design</a><a href="/#contact">Contact</a></div><div class="footer-meta"><span>Dubai · South EMEA · Southeast Asia</span><span>© ${new Date().getFullYear()} OpenGate Advisory</span></div></div></footer>`;
const siteHeader=document.querySelector('.site-header');
document.querySelector('.nav-toggle')?.addEventListener('click',e=>{const open=siteHeader.classList.toggle('mobile-open');e.currentTarget.setAttribute('aria-expanded',open);e.currentTarget.textContent=open?'×':'☰'});
document.querySelector('.nav-trigger')?.addEventListener('click',e=>{const menu=e.currentTarget.closest('.portfolio-menu');const open=menu.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',open)});
document.addEventListener('click',e=>{if(!e.target.closest('.portfolio-menu'))document.querySelector('.portfolio-menu')?.classList.remove('open')});
document.querySelectorAll('[data-tabs]').forEach(tabs=>{const buttons=tabs.querySelectorAll('.tab-button'),panels=tabs.querySelectorAll('.tab-panel');buttons.forEach(button=>button.addEventListener('click',()=>{buttons.forEach(b=>b.classList.remove('active'));panels.forEach(p=>p.classList.remove('active'));button.classList.add('active');tabs.querySelector(`#${button.dataset.target}`).classList.add('active')}))});
document.querySelectorAll('.reveal').forEach(reveal=>{const range=reveal.querySelector('input'),after=reveal.querySelector('.reveal-after'),line=reveal.querySelector('.reveal-line'),handle=reveal.querySelector('.reveal-handle');range.addEventListener('input',()=>{const value=range.value;after.style.clipPath=`inset(0 ${100-value}% 0 0)`;line.style.left=value+'%';handle.style.left=value+'%'})});

const pageClass=path==='/technology'?'technology-page':path==='/real-estate'?'real-estate-page':path==='/web-design'?'web-design-page':'home-page';
document.body.classList.add(pageClass);

if(pageClass==='home-page'){
  const technologyVisual=document.querySelector('.service-visual[href="/technology"] img');
  const marketingVisual=document.querySelector('.service-visual[href="/web-design"] img');
  if(technologyVisual){technologyVisual.src='morbit-office.jpg';technologyVisual.alt='Natural modern workplace and meeting-room technology'}
  if(marketingVisual){marketingVisual.src='strategy-whiteboard.jpg';marketingVisual.alt='Natural creative strategy workshop'}
  const teamGrid=document.querySelector('#team .team-grid');
  if(teamGrid)teamGrid.innerHTML=`<article class="person"><div class="person-head"><img src="Georges-new.png" alt="Georges Lemire"><div><h3>Georges Lemire</h3><div class="role">Founder · Principal Advisor</div></div></div><p class="person-bio">Former Managing Director France and Regional Director MEA at Cisco. Georges brings 25+ years growing enterprise technology businesses across Europe, the Middle East and Africa, supported by a practical network for companies expanding into South EMEA and Southeast Asia.</p><div class="person-highlights"><span>Managing Director France — Cisco</span><span>Regional Director Middle East & Africa — Cisco</span><span>Director Operations Sales EMEAR — Cisco</span><span>Area VP EMEA — Neat</span></div><a class="person-link" href="https://www.linkedin.com/in/georgeslemire/" target="_blank" rel="noopener">↗ LinkedIn Profile</a></article><article class="person"><div class="person-head"><img src="Dorian.jpeg" alt="Dorian Lemire"><div><h3>Dorian Lemire</h3><div class="role">Web Designer · Revenue Growth Strategist</div></div></div><p class="person-bio">Dorian designs digital experiences that turn complex offers into clear buyer journeys. His work combines positioning, responsive web design, content creation and conversion thinking for B2B, hospitality and growth-focused brands.</p><div class="person-highlights"><span>Conversion-focused UI and UX</span><span>Responsive static websites</span><span>Content systems and campaign visuals</span><span>Lead journeys and commercial messaging</span></div><a class="person-link" href="https://www.linkedin.com/in/dorian-lemire" target="_blank" rel="noopener">↗ LinkedIn Profile</a></article>`;
}

if(pageClass==='technology-page'){
  document.querySelector('.page-hero-media')?.classList.add('dashboard-frame');
  const channelImage=document.querySelector('#tab-channel img');
  if(channelImage)channelImage.src='morbit-ecosystem-dark.png';
  const metricSection=document.querySelector('.metric-row')?.closest('section');
  if(metricSection)metricSection.insertAdjacentHTML('afterend',`<section class="section technology-ecosystem"><div class="container"><div class="section-head"><div><div class="eyebrow">Connected ecosystem</div><h2 class="section-title">Every room, device and signal<br><em>in one operational story.</em></h2></div><p class="lead">Hover across the stage to explore how Morbit connects collaboration spaces, workplace hardware, environmental signals and management insight without forcing teams through disconnected tools.</p></div><div class="ecosystem-stage"><img src="morbit-ecosystem-dark.png" alt="Morbit connected workplace ecosystem"><div class="ecosystem-copy"><h3>One platform across the workplace</h3><p>From the room and its devices to the operations dashboard, the value is a simpler picture of performance—clear enough for technical teams and credible enough for senior decision-makers.</p></div></div></div></section>`);
}

const motionItems=document.querySelectorAll('.section-head,.service-visual,.capability,.person,.metric,.location-card,.work-card,.ecosystem-stage');
motionItems.forEach(item=>item.classList.add('motion-item'));
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target)}}),{threshold:.08});motionItems.forEach(item=>observer.observe(item))}else motionItems.forEach(item=>item.classList.add('in-view'));
